config/routes.rb
Podcastapp::Application.routes.draw do
 
  resources :authentications
  
  match '/auth/:provider/callback' => 'authentications#create'

  root :to => "podcasts#index"

  devise_for :users,
             :singular => :user,
             :controllers => {:registrations => 'registrations'}
             
  resources :users

  resources :episodes

  resources :podcasts do
    member do
      get 'get_update_status'
      get 'reset_update_status'
    end
    resources :episodes
    get :autocomplete_podcast_name, :on => :collection
  end
  
  match 'search', :to => 'podcasts#search'
  match 'podcasts/:id/subscribe', :to => 'users#subscribe', :as => 'subscription'

  

end

app/models/episode.rb
###################################################################################################
#
# Class: Episode
#
###################################################################################################
require 'iconv'
require 'nokogiri'
require 'httparty'
require 'will_paginate'

class Episode < ActiveRecord::Base

  belongs_to :podcast
  
  validates_uniqueness_of :title, :scope => :podcast_id

  # Define a custom logger.
  def self.episode_logger
    @@episode_logger ||= Logger.new("#{RAILS_ROOT}/log/cron/episode_cron.log", 3, 524288)
  end
  
  # Fetch the latest episodes for the podcast.
  def self.fetch_podcast_episodes(podcast, options = {})
    begin
      comet = options[:comet] || false
      
      @podcast = Podcast.find(podcast, :select => 'id, name, feedurl')
      @feed = @podcast.feedurl
      puts "#{@feed}"

      @podcast.update_attributes :episode_update_status => 'started'

      begin
        @doc = Nokogiri.XML(HTTParty.get(@feed, 'User-Agent' => 'ruby', :format => :html, :timeout => 15, :limit => 10)).remove_namespaces!
        @episodes = @doc.xpath("//item")
      rescue StandardError => ex
        puts "#{ex.class}:#{ex.message}"
      end
    
      @episodes.each do |episode|
        begin
          # Grab the episode title
          episode_title = Episode.parse_nodes(episode.at_xpath("./title"))
    
          # Let's grab the most robust shownotes we can find
          episode_shownotes_summary = Episode.parse_nodes(episode.at_xpath("./summary"))
          episode_shownotes_description = Episode.parse_nodes(episode.at_xpath("./description"))
          episode_shownotes_subtitle = Episode.parse_nodes(episode.at_xpath("./subtitle"))
    
          length = {}
          length["summary"] = episode_shownotes_summary.scan(/[\w-][\w.]+/).size unless episode_shownotes_summary.nil?
          length["description"] = episode_shownotes_description.scan(/[\w-][\w.]+/).size unless episode_shownotes_description.nil?
          length["subtitle"] = episode_shownotes_subtitle.scan(/[\w-][\w.]+/).size unless episode_shownotes_subtitle.nil?
    
          max_length = length.values.max
          shownotes = length.key(max_length)

          if shownotes == "summary"
            episode_shownotes = episode_shownotes_summary
          elsif shownotes == "description"
            episode_shownotes = episode_shownotes_description
          elsif shownotes == "subtitle"
            episode_shownotes = episode_shownotes_subtitle
          end

          # Episode publish date
          episode_pub_date = Episode.parse_nodes(episode.at_xpath("./pubDate"))

          # Episode url
          episode_url = Episode.parse_nodes(episode.at_xpath("./enclosure/@url"))
        
          if episode_url.nil?
            episode_url = Episode.parse_nodes(episode.at_xpath("./content/@url"))
          end

          # Episode file type
          episode_file_type = Episode.parse_nodes(episode.at_xpath("./enclosure/@type"))
        
          if episode_file_type.nil?
            episode_file_type = Episode.parse_nodes(episode.at_xpath("./content/@type"))
          end        

          # Episode file size
          episode_file_size = Episode.parse_nodes(episode.at_xpath("./enclosure/@length"))
        
          if episode_file_size.nil?
            episode_file_size = Episode.parse_nodes(episode.at_xpath("./content/@filesize"))
          end        
        
          episode_file_size = (episode_file_size.to_f / 1048576.0).round(1).to_s + " MB"

          # Episode Duration
          episode_duration = Episode.parse_nodes(episode.at_xpath("./duration"))
    
          unless episode_duration.nil? or episode_duration.include? ":"
            episode_duration = Time.at(episode_duration.to_i).gmtime.strftime("%R:%S")
          end
        
          episode = @podcast.episodes.find(:all, :conditions => {:title => episode_title})
        
          if (episode == [])
            begin
              episode = Episode.create(
                :podcast_id => @podcast.id,
                :title => episode_title,
                :shownotes => episode_shownotes,
                :date_published => episode_pub_date,
                :url => episode_url,
                :filetype => episode_file_type,
                :size => episode_file_size,
                :duration => episode_duration
              )
              puts "New Episode: #{episode.title}"
              Episode.episode_logger.info("New Episode: #{episode.title}")
            rescue StandardError => ex
              puts "An error of type #{ex.class} happened, message is #{ex.message}"
            end     
          elsif (!episode[0].title.nil?)
            begin
              ep = episode[0]
              ep.shownotes = episode_shownotes
              ep.date_published = episode_pub_date
              ep.url = episode_url
              ep.filetype = episode_file_type
              ep.size = episode_file_size
              ep.duration = episode_duration
            
              if ep.url_changed? or ep.shownotes_changed?
                ep.save      
                puts "Update Episode: #{episode[0].title}"
                Episode.episode_logger.info("Update Episode: #{episode[0].title}")
              end
            rescue StandardError => ex
              puts "An error of type #{ex.class} happened, message is #{ex.message}"
            end          
          end
        rescue StandardError => ex
          puts "#{ex.class}: #{ex.message}"
          @podcast.update_attributes :episode_update_status => 'error'
        end
      end
    rescue StandardError => ex
      puts "#{ex.class}: #{ex.message}"
    ensure
      @podcast.update_attributes :episode_update_status => 'success'
      unless comet
        @podcast.update_attributes :episode_update_status => 'reset'
      end
    end
  end
  
  # Return the text of the xpath result.
  def self.parse_nodes(xpath)
    node_value = xpath.text unless xpath.nil?
    return node_value
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  
  before_filter :get_required_assets 
  
  # GET /episodes
  # GET /episodes.xml
  def index
    @podcast = Podcast.find(params[:podcast_id])
    @page_title = @podcast.name + " &raquo; Episodes"
    
    # Don't bother fetching new episodes if we just did or if we're calling #index with comet
    @dont_bother = @podcast.updated_at > Time.now - 10.minutes || params[:reload] == "true"
    
    unless @dont_bother
      # Fetch new episodes in a background task
      Episode.delay.fetch_podcast_episodes(@podcast, :comet => true)
    end
    
    # Find all podcast episodes and sort by date descending
    @episodes = @podcast.episodes.all.sort {|a, b|
      if a.date_published.nil? or b.date_published.nil?
        b.date_published <=> a.date_published
      else
        b.date_published.to_time <=> a.date_published.to_time
      end
    }.paginate :page => params[:page], :per_page => 10

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @episodes }
      format.js { render :layout => false }
    end
  end

  # GET /episodes/1
  # GET /episodes/1.xml
  def show
    @episode = Episode.find(params[:id])
    @page_title = @episode.podcast.name + " &raquo; " + Iconv.iconv('ascii//translit', 'utf-8', @episode.title).join("").truncate(35)


    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @episode }
    end
  end

  # GET /episodes/new
  # GET /episodes/new.xml
  def new
    @episode = Episode.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @episode }
    end
  end

  # GET /episodes/1/edit
  def edit
    @episode = Episode.find(params[:id])
  end

  # POST /episodes
  # POST /episodes.xml
  def create
    @episode = Episode.new(params[:episode])

    respond_to do |format|
      if @episode.save
        format.html { redirect_to(@episode, :notice => 'Episode was successfully created.') }
        format.xml  { render :xml => @episode, :status => :created, :location => @episode }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @episode.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /episodes/1
  # PUT /episodes/1.xml
  def update
    @episode = Episode.find(params[:id])

    respond_to do |format|
      if @episode.update_attributes(params[:episode])
        format.html { redirect_to(@episode, :notice => 'Episode was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @episode.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /episodes/1
  # DELETE /episodes/1.xml
  def destroy
    @episode = Episode.find(params[:id])
    @episode.destroy

    respond_to do |format|
      format.html { redirect_to(episodes_url) }
      format.xml  { head :ok }
    end
  end
  
  def get_required_assets
    @asset_group_css = :episodes 
  end
end

app/helpers/episodes_helper.rb
module EpisodesHelper
  
  def clean_shownotes(html)
    @shownotes = raw html
  end
  
end

app/views/episodes/_form.html.erb
<%= form_for(@episode) do |f| %>
  <% if @episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
      <% @episode.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :shownotes %><br />
    <%= f.text_area :shownotes %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :filetype %><br />
    <%= f.text_field :filetype %>
  </div>
  <div class="field">
    <%= f.label :size %><br />
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.text_field :duration %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing episode</h1>

<%= render 'form' %>

<%= link_to 'Show', @episode %> |
<%= link_to 'Back', episodes_path %>

app/views/episodes/index.html.erb
<h2><%= link_to @podcast.name, podcast_path(@podcast) %></h2>

<div id="status"></div>

<div id="episodes">

  <% @episodes.each do |episode| %>
			<div class="podcast-episode">
	      <h3 class="episode-title"><%= link_to episode.title, episode.url %></h3>
				<div class="episode-meta clearfix">
					<span class="filetype"><%= episode.filetype %></span>
		      <span class="filesize"><%= episode.size unless episode.size == "0.0 MB" %></span>
		      <span class="duration"><%= episode.duration %></span>
				</div>
	      <div class="shownotes"><%= clean_shownotes(episode.shownotes) %></div>
				<div class="buttons">
	      	<%= link_to 'Show', episode, {:class => "button"} %>
	      	<%= link_to 'Edit', edit_episode_path(episode), {:class => "button"} %>
	      	<%= link_to 'Destroy', episode, :confirm => 'Are you sure?', :method => :delete, :class => "button negative" %>
				</div>
			</div>
  <% end %>

</div>

<div class="pagination-wrapper"><%= will_paginate @episodes %></div>

<% unless @dont_bother %>
	<%= javascript_tag do %>
	  $(function(){
	    podcast = <%= @podcast.id %>
 
	    // Suppress useless ReferenceErrors
	    started = ""
	    success = ""
	    error = ""
			reset = ""
 
	    // Fetch new episodes on page load with ajax polling
	    function fetch_new_episodes() {
	      $("#status").html("<p>Fetching New Episodes</p>");
	      $.ajax({
	        type: "GET",
	        url: "<%= DOMAIN_NAME %>/podcasts/" + podcast + "/get_update_status",
	        success: function(data){
	          if (data == "success") {
	            $("#episodes").load("<%= DOMAIN_NAME %>/podcasts/" + podcast + "/episodes?reload=true #episodes", function(){
	              $("#status").html("<p>Episodes Updated</p>");
								$.get("<%= DOMAIN_NAME %>/podcasts/" + podcast + "/reset_update_status", function(data){
									console.log(data);
								});
	            });
	          } else {
	            fetch_new_episodes();
	          }
	        }
	      });      
	    }
		  fetch_new_episodes();
	  });
	<% end %>
<% end %>

app/views/episodes/new.html.erb
<h1>New episode</h1>

<%= render 'form' %>

<%= link_to 'Back', episodes_path %>

app/views/episodes/show.html.erb
<div class="podcast-episode">
  <h3 class="episode-title"><%= link_to @episode.title, @episode.url %></h3>
	<div class="episode-meta clearfix">
		<span class="filetype"><%= @episode.filetype %></span>
    <span class="filesize"><%= @episode.size unless @episode.size == "0.0 MB" %></span>
    <span class="duration"><%= @episode.duration %></span>
	</div>
  <div class="shownotes"><%= clean_shownotes(@episode.shownotes) %></div>
	<div class="buttons">
		<%= link_to 'Edit', edit_episode_path(@episode), {:class => "button"} %>
		<%= link_to 'Back', :back, {:class => "button"} %>
	</div>
</div>