config/routes.rb
Podcastapp::Application.routes.draw do
 
  resources :authentications
  
  match '/auth/:provider/callback' => 'authentications#create'

  root :to => "podcasts#index"

  devise_for :users,
             :singular => :user,
             :controllers => {:registrations => 'registrations'}
             
  resources :users

  resources :episodes

  resources :podcasts do
    member do
      get 'get_update_status'
      get 'reset_update_status'
    end
    resources :episodes
    get :autocomplete_podcast_name, :on => :collection
  end
  
  match 'search', :to => 'podcasts#search'
  match 'podcasts/:id/subscribe', :to => 'users#subscribe', :as => 'subscription'

  

end

app/models/podcast.rb
###################################################################################################
#
# Class: Podcast
#
###################################################################################################
require 'nokogiri'
require 'httparty'
require 'will_paginate'

class Podcast < ActiveRecord::Base
  
  has_many :episodes, :dependent => :destroy
  has_and_belongs_to_many :users
  
  validates_uniqueness_of :name
  
  cattr_reader :per_page
  @@per_page = 50
  
  searchable do
    text :name
  end
  
  # Define a custom logger.
  def self.podcast_logger
    @@podcast_logger ||= Logger.new("#{RAILS_ROOT}/log/cron/podcast_cron.log", 3, 524288)
  end
  
  # Generate the iTunes top 300 podcasts url (overall).    
  def self.itunes_top_rss
    itunes_url = "http://itunes.apple.com/us/rss/toppodcasts/limit=300/explicit=true/xml"
    itunes_doc = Nokogiri.HTML(HTTParty.get(itunes_url, :format => :html))
    
    # Scrape that url
    Podcast.scrape_from_itunes(itunes_doc)    
  end
  
  # Generate the iTunes top 300 podcasts url (by genre).
  def self.itunes_genre_rss
    itunes_genre_codes = {}
    
      itunes_genre_codes['arts'] = "1301"
      itunes_genre_codes['business'] = "1321"
      itunes_genre_codes['comedy'] = "1303"
      itunes_genre_codes['education'] = "1304"
      itunes_genre_codes['games_hobbies'] = "1323"
      itunes_genre_codes['goverment_organization'] = "1325"
      itunes_genre_codes['health'] = "1307"
      itunes_genre_codes['kids_family'] = "1305"
      itunes_genre_codes['music'] = "1310"
      itunes_genre_codes['news_politics'] = "1311"
      itunes_genre_codes['religion_spirituality'] = "1314"
      itunes_genre_codes['science_medicine'] = "1315"
      itunes_genre_codes['society_culture'] = "1324"
      itunes_genre_codes['sports_recreation'] = "1316"
      itunes_genre_codes['technology'] = "1318"
      itunes_genre_codes['tv_film'] = "1309"

    itunes_genre_codes.each do |genre, id|
      
      # Create the top 300 url for each genre
      itunes_url = "http://itunes.apple.com/us/rss/toppodcasts/limit=300/genre=#{id}/explicit=true/xml"
      itunes_doc = Nokogiri.HTML(HTTParty.get(itunes_url, :format => :html))
      
      # Scrape that url
      Podcast.scrape_from_itunes(itunes_doc)  
    end
  end 
  
  # Parse the xml returned by iTunes.  
  # If the podcast exists, update attributes.  
  # Otherwise, create a new podcast.
  def self.scrape_from_itunes(itunes_doc)
    itunes_doc.xpath('//feed/entry').map do |entry|
      new_name = entry.xpath("./name").text
      podcast = Podcast.find_all_by_name(new_name)
      if (podcast == [])
        begin
          podcast = Podcast.create(
            :name => entry.xpath("./name").text,
            :itunesurl => entry.xpath("./link/@href").text,
            :category => entry.xpath("./category/@term").text,
            :hosts => entry.xpath("./artist").text,
            :description => entry.xpath("./summary").text,
            :artwork => entry.xpath("./image[@height='170']").text  
          )
          puts "New Podcast: #{podcast.name}"
          Podcast.podcast_logger.info("New Podcast: #{podcast.name}")
        rescue StandardError => ex
          puts "An error of type #{ex.class} happened, message is #{ex.message}"
        end
      elsif (!podcast[0].nil?)
        begin
          pod = podcast[0]
          pod.itunesurl = entry.xpath("./link/@href").text
          pod.category = entry.xpath("./category/@term").text
          pod.hosts = entry.xpath("./artist").text
          pod.description = entry.xpath("./summary").text
          pod.artwork = entry.xpath("./image[@height='170']").text
          
          if pod.changed?
            pod.save      
            puts "Update Podcast: #{pod.name}"
            Podcast.podcast_logger.info("Update Podcast: #{pod.name}")
          end
        rescue StandardError => ex
          puts "An error of type #{ex.class} happened, message is #{ex.message}"
        end
      else
        puts "StandardError"
      end
    end
  end  
  
  # Scrape the podcast site url and feed url from the iTunes doc.
  def self.site_and_feed_discovery(options = {})
    new_podcasts_only = options[:new_podcasts_only] || false
    if new_podcasts_only
      podcast = Podcast.find(:all, :select => 'id, itunesurl, name', :conditions => ['created_at > ?', Time.now - 24.hours])
      Podcast.podcast_logger.info("#{podcast.count}")
    else
      podcast = Podcast.find(:all, :select => 'id, itunesurl, name')
    end
    podcast.each do | pod |
      begin
        url_hash = Imasquerade::Extractor.parse_itunes_uri(pod.itunesurl)
        
        pod.feedurl = url_hash["feedurl"]
        pod.siteurl = url_hash["siteurl"]
        
        if pod.feedurl_changed? or pod.siteurl_changed?
          pod.save
          puts "#{pod.feedurl}"
          puts "#{pod.siteurl}"
          Podcast.podcast_logger.info("#{pod.feedurl}")
          Podcast.podcast_logger.info("#{pod.siteurl}")
        end
      rescue StandardError => ex
        puts "An error of type #{ex.class} happened, message is #{ex.message}"
      end
    end
  end  

  # Scrape the podcast twitter and facebook urls from the site doc.
  def self.social_discovery(options = {})
    new_podcasts_only = options[:new_podcasts_only] || false
    if new_podcasts_only
      podcast = Podcast.find(:all, :select => 'id, siteurl, name', :conditions => ['created_at > ?', Time.now - 24.hours])
      Podcast.podcast_logger.info("#{podcast.count}")
    else
      podcast = Podcast.find(:all, :select => 'id, siteurl, name')
    end
    
    # TODO Handle Nokogiri Errno:: Errors
    podcast.each do | pod |
      puts "#{pod.name}"
      begin 
        # Make sure the url is readable by httparty
        if pod.siteurl.include? 'http://'
          pod_site = pod.siteurl
        else
          pod_site = pod.siteurl.insert 0, "http://"
        end
 
        # Skip all of this if we're dealing with a feed
        unless pod_site.downcase =~ /.rss|.xml|libsyn/i
          begin
            pod_doc = Nokogiri.HTML(HTTParty.get(pod_site, 'User-Agent' => 'ruby', :timeout => 15, :limit => 10))
          rescue HTTParty::UnsupportedURIScheme => ex
            dir = ex.message.split("'")[1]
            pod_site = "http://" + pod_site.split("/")[2] + dir
            pod_doc = Nokogiri.HTML(HTTParty.get(pod_site, 'User-Agent' => 'ruby', :timeout => 15, :limit => 10))
          end
          pod_name_fragment = pod.name.split(" ")[0].to_s
          if pod_name_fragment.downcase == "the" or pod_name_fragment.downcase == "a"
            pod_name_fragment = pod.name.split(" ")[1].to_s unless pod.name.split(" ")[1].to_s.nil?
          end
          doc_links = pod_doc.css('a')
          
          # If a social url contains part of the podcast name, grab that.  
          # If not, grab the first one you find within our conditions.  
          # Give Nokogiri some room to breathe with pessimistic StandardError handling.
          begin
            twitter_url = Podcast.social_relevance(doc_links, "twitter.com", pod_name_fragment, "share|status")
            facebook_url = Podcast.social_relevance(doc_links, "facebook.com", pod_name_fragment, "share|.event|placement=")
          # Ensure that the urls get saved regardless of what else happens
          ensure
            pod.twitter = twitter_url
            pod.facebook = facebook_url
            
            if pod.twitter_changed? or pod.facebook_changed?
              pod.save
              puts "#{twitter_url}"
              puts "#{facebook_url}"
              Podcast.podcast_logger.info("#{twitter_url}")
              Podcast.podcast_logger.info("#{facebook_url}")
            end
          end
        end
      rescue StandardError => ex
        puts "FINAL StandardError: #{ex.class} + #{ex.message}"
      end
    end  
  end
  
  # If a social url contains part of the podcast name, grab that.  
  # If not, grab the first one you find within our conditions.  
  # Give Nokogiri some room to breathe with pessimistic StandardError handling.  
  def self.social_relevance(doc_links, social_network, pod_name_fragment, regex)
    begin
      begin       
        social_links = doc_links.find {|link| link['href'].to_s.match(/#{social_network}/i) and link['href'].to_s.match(/#{pod_name_fragment}/i).to_s != "" unless link['href'].to_s.match(/#{regex}/i)}.attribute('href').to_s 
      rescue StandardError
        if doc_links.find {|link| link['href'].to_s.match(/#{social_network}/i) unless link['href'].to_s.match(/#{regex}/i)}.nil?
          social_links = nil
        else       
          social_links = doc_links.find {|link| link['href'].to_s.match(/#{social_network}/i) unless link['href'].to_s.match(/#{regex}/i)}.attribute('href').to_s
        end
      end
    rescue StandardError
      # Ensure that the urls get saved regardless of what else happens
    ensure
      return social_links.to_s    
    end
  end
  
  # Fetch twitter handle from twitter url
  def self.fetch_twitter_handle(options = {})
    new_podcasts_only = options[:new_podcasts_only] || false
    if new_podcasts_only
      podcast = Podcast.find(:all, :select => 'id, twitter, name', :conditions => ['created_at > ? AND twitter IS NOT ? AND twitter != ?', Time.now - 24.hours, nil, ''])
      Podcast.podcast_logger.info("#{podcast.count}")
    else
      podcast = Podcast.find(:all, :select => 'id, twitter, name', :conditions => ['twitter IS NOT ? AND twitter != ?', nil, ''])
    end
    
    podcast.each do | pod |
      begin
        pod_twitter = pod.twitter.gsub("#!/","")
        # Make sure the url is readable by httparty
        unless pod_twitter.include? 'http://'
          pod_twitter = pod_twitter.insert 0, "http://"
        end
        unless pod_twitter.include? "search?q="
          puts "#{pod_twitter}"
          Podcast.podcast_logger.info("#{pod_twitter}")

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  
  autocomplete :podcast, :name
  
  # GET /podcasts
  # GET /podcasts.xml
  def index
    @page_title = false
    @podcasts = Podcast.paginate :page => params[:page], :per_page => 50
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @podcasts }
    end
  end
  
  # Search podcasts
  def search
    @page_title = "Search"
    @search = Sunspot.search(Podcast) do
      keywords(params[:q])
      paginate(:page => params[:page])
    end
    
    @result_count = @search.total
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @podcasts }
    end
  end
  
  # Return episode update status to ajax request
  def get_update_status
    @podcast = Podcast.find(params[:id])

    respond_to do |format|
      format.js { render :json => @podcast.episode_update_status }
    end
  end
  
  # Reset update status after successful update
  def reset_update_status
    @podcast = Podcast.find(params[:id])
    @podcast.update_attributes :episode_update_status => "reset"

    respond_to do |format|
      format.js { render :json => "reset" }
    end
  end

  # GET /podcasts/1
  # GET /podcasts/1.xml
  def show
    @podcast = Podcast.find(params[:id])
    @pod_name = Podcast.find(@podcast).name
    @page_title = @pod_name
    
    if current_user && current_user.podcasts.include?(@podcast)
      @subscribed = true
    else
      @subscribed = false
    end

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @podcast }
    end
  end

  # GET /podcasts/new
  # GET /podcasts/new.xml
  def new
    @podcast = Podcast.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @podcast }
    end
  end

  # GET /podcasts/1/edit
  def edit
    @podcast = Podcast.find(params[:id])
  end

  # POST /podcasts
  # POST /podcasts.xml
  def create
    @podcast = Podcast.new(params[:podcast])

    respond_to do |format|
      if @podcast.save
        format.html { redirect_to(@podcast, :notice => 'Podcast was successfully created.') }
        format.xml  { render :xml => @podcast, :status => :created, :location => @podcast }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @podcast.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /podcasts/1
  # PUT /podcasts/1.xml
  def update
    @podcast = Podcast.find(params[:id])

    respond_to do |format|
      if @podcast.update_attributes(params[:podcast])
        format.html { redirect_to(@podcast, :notice => 'Podcast was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @podcast.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /podcasts/1
  # DELETE /podcasts/1.xml
  def destroy
    @podcast = Podcast.find(params[:id])
    @podcast.destroy

    respond_to do |format|
      format.html { redirect_to(podcasts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/views/podcasts/_form.html.erb
<%= form_for(@podcast) do |f| %>
  <% if @podcast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@podcast.errors.count, "error") %> prohibited this podcast from being saved:</h2>

      <ul>
      <% @podcast.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :siteurl %><br />
    <%= f.text_field :siteurl %>
  </div>
  <div class="field">
    <%= f.label :itunesurl %><br />
    <%= f.text_field :itunesurl %>
  </div>
  <div class="field">
    <%= f.label :feedurl %><br />
    <%= f.text_field :feedurl %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :hosts %><br />
    <%= f.text_field :hosts %>
  </div>
  <div class="field">
    <%= f.label :twitter %><br />
    <%= f.text_field :twitter %>
  </div>
  <div class="field">
    <%= f.label :facebook %><br />
    <%= f.text_field :facebook %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :artwork %><br />
    <%= f.text_field :artwork %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/podcasts/edit.html.erb
<h1>Editing podcast</h1>

<%= render 'form' %>

<div class="buttons">
	<%= link_to 'Show', @podcast, {:class => "button"} %>
	<%= link_to 'Back', podcasts_path, {:class => "button"} %>
</div>

app/views/podcasts/index.html.erb
<div class="inner-wrapper clearfix">
	<% @podcasts.each do |podcast| %>
		<div class="podcast">
			<h2 class="name"><%= link_to podcast.name, podcast_path(podcast) %></h2>
			<%= link_to image_tag(podcast.artwork, :border=>0), podcast_path(podcast), :class => "artwork" %>
			<div class="meta-wrapper">
				<a class="siteurl" href="<%= podcast.siteurl %>"><%= podcast.siteurl %></a><br />
				<a class="itunesurl" href="<%= podcast.itunesurl %>"><%= podcast.itunesurl %></a><br />
				<a class="feedurl" href="<%= podcast.feedurl %>"><%= podcast.feedurl %></a><br />
				<span class="category"><%= podcast.category %></span><br />
				<span class="hosts"><%= podcast.hosts %></span><br />
				<a class="twitter" href="<%= podcast.twitter %>"><%= podcast.twitter %></a><br />
				<a class="facebook" href="<%= podcast.facebook %>"><%= podcast.facebook %></a><br />
				<p class="description"><%= podcast.description %></p>
			</div>
			<div class="buttons">
				<%= link_to 'Show', podcast, {:class => "button"} %>
				<%= link_to 'Edit', edit_podcast_path(podcast), {:class => "button"} %>
				<%= link_to 'Destroy', podcast, :confirm => 'Are you sure?', :method => :delete, :class => "button negative" %>
			</div>
		</div>
	<% end %>
</div>

<div class="pagination-wrapper"><%= will_paginate @podcast %></div>

app/views/podcasts/new.html.erb
<h1>New podcast</h1>

<%= render 'form' %>

<%= link_to 'Back', podcasts_path, {:class => "button"} %>

app/views/podcasts/search.html.erb
<div class="search">
	<%= form_tag(search_path, :method => "get", :id => "podcast_search") do |f| %>
	  <%= label_tag(:q, "Search for:") %>
	  <%= autocomplete_field_tag 'q', '', autocomplete_podcast_name_podcasts_path, :size => 50 %>
	  <%= submit_tag("Search", :class => "submit") %>
	<% end %>
</div>

<h1>Searching podcasts (<%= @result_count %>)</h1>

<div class="results">
  <% @search.each_hit_with_result do |hit, podcast| -%>
    <div class="result">
      <h4><%= link_to podcast.name, podcast %></h4>
    </div>
  <% end -%>
</div>

<div class="pagination-wrapper">
	<%= will_paginate @search.hits %>
</div>

<%= javascript_tag do %>
	$(function(){
		$('#q').bind('railsAutocomplete.select', function(){
			alert("yes");
		});
	});
<% end %>

app/views/podcasts/show.html.erb
<h2><%= link_to @pod_name, podcast_path(@podcast) %></h2>

<div class="meta">
	<p>
	  <b>Siteurl:</b>
	  <%= link_to @podcast.siteurl, @podcast.siteurl %>
	</p>

	<p>
	  <b>Itunesurl:</b>
	  <%= link_to @podcast.itunesurl, @podcast.itunesurl %>
	</p>

	<p>
	  <b>Feedurl:</b>
	  <%= link_to @podcast.feedurl, @podcast.feedurl %>
	</p>

	<p>
	  <b>Category:</b>
	  <%= @podcast.category %>
	</p>

	<p>
	  <b>Hosts:</b>
	  <%= @podcast.hosts %>
	</p>

	<p>
	  <b>Twitter:</b>
	  <%= link_to @podcast.twitter, @podcast.twitter %>
	</p>

	<p>
	  <b>Facebook:</b>
	  <%= link_to @podcast.facebook, @podcast.facebook %>
	</p>

	<p>
	  <b>Description:</b>
	  <%= @podcast.description %>
	</p>
</div>

<%= link_to image_tag(@podcast.artwork, :class => "artwork", :alt => @pod_name, :border=>0), podcast_path(@podcast) %>

<% if current_user %>
	<div class="buttons">
		<% if @subscribed == false %>
			<%= link_to "Subscribe", subscription_path(@podcast), :class => "big button" %>
		<% else %>
			<%= content_tag(:span, "Already Subscribed", :class => "disabled big button") %>
		<% end %>
	</div>
<% end %>

<div class="buttons">
	<%= link_to 'Episodes', podcast_episodes_path(@podcast), {:class => "button"} %>
	<%= link_to 'Edit', edit_podcast_path(@podcast), {:class => "button"} %>
	<%= link_to 'Back', :back, {:class => "button"} %>
</div>